Repository mdtanjimrahman/SkyQuest-Arcade-OpenGL, pull requests merged in 2025-01, with the labels that each got.

#11 Add animation for level 2
  SkyQuest-Arcade/SkyQuest-Arcade.depend
  SkyQuest-Arcade/SkyQuest-Arcade.layout
  SkyQuest-Arcade/bin/Debug/SkyQuest-Arcade.exe
  SkyQuest-Arcade/main.cpp
  SkyQuest-Arcade/obj/Debug/main.o
Labels: enhancement

#12 Animation bug fixed for level 3
  SkyQuest-Arcade/SkyQuest-Arcade.depend
  SkyQuest-Arcade/SkyQuest-Arcade.layout
  SkyQuest-Arcade/bin/Debug/SkyQuest-Arcade.exe
  SkyQuest-Arcade/main.cpp
  SkyQuest-Arcade/obj/Debug/main.o
Labels: bug

#15 Add Text file for store highest score
  SkyQuest-Arcade/SkyQuest-Arcade.depend
  SkyQuest-Arcade/SkyQuest-Arcade.layout
  SkyQuest-Arcade/bin/Debug/SkyQuest-Arcade.exe
  SkyQuest-Arcade/main.cpp
  SkyQuest-Arcade/obj/Debug/main.o
Labels: enhancement

#19 Add sound effect
  SkyQuest-Arcade/SkyQuest-Arcade.depend
  SkyQuest-Arcade/bin/Debug/SkyQuest-Arcade.exe
  SkyQuest-Arcade/main.cpp
  SkyQuest-Arcade/obj/Debug/main.o
Labels: enhancement

#21 Sound stop bug fixed
  SkyQuest-Arcade/bin/Debug/SkyQuest-Arcade.exe
  SkyQuest-Arcade/main.cpp
  SkyQuest-Arcade/obj/Debug/main.o
Labels: bug

#22 Sound add for level1 and level2. Also store level1 highest score
  SkyQuest-Arcade/SkyQuest-Arcade.depend
  SkyQuest-Arcade/bin/Debug/SkyQuest-Arcade.exe
  SkyQuest-Arcade/bin/Debug/obstacle_hit.wav
  SkyQuest-Arcade/highest_scores.txt
  SkyQuest-Arcade/main.cpp
  SkyQuest-Arcade/obj/Debug/main.o
Labels: enhancement

#23 Animation speed bug fixed
  SkyQuest-Arcade/SkyQuest-Arcade.depend
  SkyQuest-Arcade/SkyQuest-Arcade.layout
  SkyQuest-Arcade/bin/Debug/SkyQuest-Arcade.exe
  SkyQuest-Arcade/highest_scores.txt
  SkyQuest-Arcade/main.cpp
  SkyQuest-Arcade/obj/Debug/main.o
Labels: bug

#24 Timer add on level 1
  SkyQuest-Arcade/SkyQuest-Arcade.depend
  SkyQuest-Arcade/bin/Debug/SkyQuest-Arcade.exe
  SkyQuest-Arcade/main.cpp
  SkyQuest-Arcade/obj/Debug/main.o
Labels: enhancement

#25 Add highest score for level1 and level2
  SkyQuest-Arcade/SkyQuest-Arcade.layout
  SkyQuest-Arcade/bin/Debug/SkyQuest-Arcade.exe
  SkyQuest-Arcade/highest_scores.txt
  SkyQuest-Arcade/main.cpp
  SkyQuest-Arcade/obj/Debug/main.o
Labels: enhancement

#27 Item and obstacle position reset
  SkyQuest-Arcade/bin/Debug/SkyQuest-Arcade.exe
  SkyQuest-Arcade/main.cpp
  SkyQuest-Arcade/obj/Debug/main.o
Labels: enhancement

#28 Aircraft border transparent
  SkyQuest-Arcade/bin/Debug/SkyQuest-Arcade.exe
  SkyQuest-Arcade/main.cpp
  SkyQuest-Arcade/obj/Debug/main.o
Labels: enhancement

#30 Add sound and also control instruction page
  SkyQuest-Arcade/SkyQuest-Arcade.depend
  SkyQuest-Arcade/bin/Debug/SkyQuest-Arcade.exe
  SkyQuest-Arcade/highest_scores.txt
  SkyQuest-Arcade/main.cpp
  SkyQuest-Arcade/obj/Debug/main.o
  how 4236d85
Labels: bug, enhancement

#32 Menu level selection bug fixed
  SkyQuest-Arcade/bin/Debug/SkyQuest-Arcade.exe
  SkyQuest-Arcade/main.cpp
  SkyQuest-Arcade/obj/Debug/main.o
Labels: bug

#33 Cover page added
  SkyQuest-Arcade/SkyQuest-Arcade.depend
  SkyQuest-Arcade/bin/Debug/SkyQuest-Arcade.exe
  SkyQuest-Arcade/highest_scores.txt
  SkyQuest-Arcade/main.cpp
  SkyQuest-Arcade/obj/Debug/main.o
Labels: enhancement

#34 Game over window redesigned
  SkyQuest-Arcade/SkyQuest-Arcade.depend
  SkyQuest-Arcade/SkyQuest-Arcade.layout
  SkyQuest-Arcade/bin/Debug/SkyQuest-Arcade.exe
  SkyQuest-Arcade/main.cpp
  SkyQuest-Arcade/obj/Debug/main.o
Labels: enhancement
